name: A workflow for test action
on: push

jobs:
  build:
    name: test action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: ./actions/test